### ISSUE TITLE
ubuntu 18  make error cmpWPkg.o object

### ISSUE THREAD

**Issue by kandido** [ActiveState/tdk#5]
Hello,
I am trying to work with tdk debugger on Ubuntu 18.04. After clone the repository for make the compiler in ../tdk/lib/tclcompiler -> ./configure  && make ... it get the error:

`cmpWPkg.c:72:26: error: ‘TdkLicenseObjCmd’ undeclared here (not in a function); did you mean ‘Tcl_UnsetObjCmd’?
     { "tdk_license",     TdkLicenseObjCmd, 1 },
                          ^~~~~~~~~~~~~~~~
                          Tcl_UnsetObjCmd
Makefile:242: failed in instructions for the object 'cmpWPkg.o'
make: *** [cmpWPkg.o] Error 1
`

How can I fix the "TdkLicenseObjCmd undeclared" error?

Thanks in advance
Candido

**Comment by cyangy** [comment]
This function looks like it checks the valid ActiveState license. The better way is to bypass it, see [this commit](https://github.com/ActiveState/tdk/commit/e086d8f0dddf5dc37cf4a19c23e0e4ccf1ab4fbe)
